# Generated by Django 2.0.2 on 2018-03-01 10:31

from django.conf import settings
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaigaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, verbose_name='微信开放id')),
                ('session_key', models.CharField(max_length=64, verbose_name='微信session key')),
                ('bearer', models.CharField(blank=True, max_length=64, null=True, verbose_name='taiga token')),
                ('related_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='关联id')),
                ('extra', jsonfield.fields.JSONField(verbose_name='扩展数据')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '微信用户Taiga关联',
                'verbose_name_plural': '微信用户Taiga关联',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=64, verbose_name='微信昵称')),
                ('avatar_url', models.URLField(default='', max_length=128, verbose_name='微信头像链接')),
                ('country', models.CharField(default='', max_length=32, verbose_name='国家')),
                ('province', models.CharField(default='', max_length=32, verbose_name='省份')),
                ('city', models.CharField(default='', max_length=32, verbose_name='城市')),
                ('gender', models.CharField(default='', max_length=8, verbose_name='性别')),
                ('language', models.CharField(default='', max_length=32, verbose_name='语言')),
            ],
            options={
                'verbose_name': '微信的userInfo',
                'verbose_name_plural': '微信的userInfo',
            },
        ),
        migrations.AddField(
            model_name='taigauser',
            name='user_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='taiga.UserInfo'),
        ),
    ]
