# Generated by Django 2.0.2 on 2018-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taiga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=128, null=True, verbose_name='微信头像链接'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='city',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='country',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='微信昵称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='province',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='省份'),
        ),
    ]
