# Generated by Django 2.0.2 on 2018-03-21 08:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taiga', '0002_auto_20180314_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='taigauser',
            name='settings',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='配置数据'),
        ),
        migrations.AlterField(
            model_name='taigauser',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, null=True, verbose_name='扩展数据'),
        ),
    ]
