# Generated by Django 2.0.2 on 2018-03-21 08:52

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True, verbose_name='项目id')),
                ('type', models.CharField(choices=[('milestone', '里程碑'), ('userstory', '用户故事'), ('task', '任务'), ('issue', '问题'), ('wikipage', 'wikipage'), ('test', '测试')], max_length=32, verbose_name='类型')),
                ('action', models.CharField(choices=[('create', '新建'), ('change', '修改'), ('delete', '删除'), ('test', '测试')], max_length=32, verbose_name='操作类型')),
                ('by', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='操作人')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='操作时间')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='负载数据')),
                ('change', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='变化对比')),
                ('is_read', models.BooleanField(default=False, verbose_name='已读')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
    ]
